In [5]:
##Task 1. Load & Understand the Data

In [6]:
import pandas as pd
import numpy as np

In [7]:

df = pd.read_csv('/content/Final_Project_dataset (1).csv')

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [8]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
print("Dataset Shape:", df.shape)
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Dataset Shape: (3900, 19)
Number of Rows: 3900
Number of Columns: 19

In [10]:
print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Column Names:
['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Payment Method', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Preferred Payment Method', 'Frequency of Purchases']

Data Types:
Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

In [12]:
##Task 2. Data Quality

In [13]:
missing_values = df.isnull().sum()

print("Missing Values per Column:")
print(missing_values)

print("\nTotal Missing Values:", df.isnull().sum().sum())

Missing Values per Column:
Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

Total Missing Values: 0

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
print(df.dtypes)

Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [17]:
##Task 3. Descriptive Statistics

In [27]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [28]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Credit Card,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,696,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [19]:
summary = pd.DataFrame({
    'Count': numeric_df.count(),
    'Sum': numeric_df.sum(),
    'Average': numeric_df.mean(),
    'Minimum': numeric_df.min(),
    'Maximum': numeric_df.max()
})

summary

                       Count        Sum      Average  Minimum  Maximum
Customer ID             3900  7606950.0  1950.500000      1.0   3900.0
Age                     3900   171867.0    44.068462     18.0     70.0
Purchase Amount (USD)   3900   233081.0    59.764359     20.0    100.0
Review Rating           3900    14624.8     3.749949      2.5      5.0
Previous Purchases      3900    98871.0    25.351538      1.0     50.0

In [21]:
##Task 4. Exploratory Analysis

In [29]:

df["Category"].value_counts()

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

In [30]:

# Analysis 1: Frequency of product categories
category_frequency = df["Category"].value_counts()

print("Purchase Records by Category:")
print(category_frequency)

category_percentage = (category_frequency / len(df) * 100).round(2)
print("\nCategory Percentages:")
print(category_percentage)

Purchase Records by Category:
Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

Category Percentages:
Category
Clothing       44.54
Accessories    31.79
Footwear       15.36
Outerwear       8.31
Name: count, dtype: float64

In [31]:
# Analysis 2: Total purchase amount by category
category_sales = (
    df.groupby("Category")["Purchase Amount (USD)"]
    .sum()
    .sort_values(ascending=False)
)

print("Total Purchase Amount by Category:")
print(category_sales)

Total Purchase Amount by Category:
Category
Clothing       104264
Accessories     74200
Footwear        36093
Outerwear       18524
Name: Purchase Amount (USD), dtype: int64

In [32]:

# Analysis 3: Average purchase amount by season and category
season_category = (
    df.groupby(["Season", "Category"])["Purchase Amount (USD)"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

print("Average Purchase Amount by Season and Category:")
print(season_category)

print("\nHighest Average:")
print(season_category.head(1))

print("\nLowest Average:")
print(season_category.tail(1))

Average Purchase Amount by Season and Category:
Season  Category
Fall    Footwear       63.71
        Clothing       61.41
        Accessories    61.34
Spring  Clothing       61.00
Summer  Accessories    60.99
Winter  Clothing       60.88
        Footwear       60.57
        Accessories    60.37
Fall    Outerwear      59.76
Summer  Footwear       58.71
Spring  Footwear       58.62
Summer  Outerwear      57.04
Winter  Outerwear      57.02
Summer  Clothing       56.56
Spring  Accessories    56.50
        Outerwear      54.63
Name: Purchase Amount (USD), dtype: float64

Highest Average:
Season  Category
Fall    Footwear    63.71
Name: Purchase Amount (USD), dtype: float64

Lowest Average:
Season  Category
Spring  Outerwear    54.63
Name: Purchase Amount (USD), dtype: float64

In [33]:
# Analysis 4: Average review rating by category
category_rating = (
    df.groupby("Category")["Review Rating"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

print("Average Review Rating by Category:")
print(category_rating)

print("\nHighest Rated Category:")
print(category_rating.head(1))

print("\nLowest Rated Category:")
print(category_rating.tail(1))

Average Review Rating by Category:
Category
Footwear       3.79
Accessories    3.77
Outerwear      3.75
Clothing       3.72
Name: Review Rating, dtype: float64

Highest Rated Category:
Category
Footwear    3.79
Name: Review Rating, dtype: float64

Lowest Rated Category:
Category
Clothing    3.72
Name: Review Rating, dtype: float64

In [ ]:
##Task 5. Findings

In [34]:
# Finding 1: Product Category Frequency

category_counts = df["Category"].value_counts()
category_percentages = (df["Category"].value_counts(normalize=True) * 100).round(2)

category_summary = pd.DataFrame({
    "Count": category_counts,
    "Percentage (%)": category_percentages
})

print(category_summary)

             Count  Percentage (%)
Category
Clothing      1737           44.54
Accessories   1240           31.79
Footwear       599           15.36
Outerwear      324            8.31

In [35]:
# Finding 2: Gender Distribution

gender_counts = df["Gender"].value_counts()
gender_percentages = (df["Gender"].value_counts(normalize=True) * 100).round(2)

gender_summary = pd.DataFrame({
    "Count": gender_counts,
    "Percentage (%)": gender_percentages
})

print(gender_summary)

        Count  Percentage (%)
Gender
Male     2652            68.0
Female   1248            32.0

In [36]:
# Finding 3: Purchase Amount Statistics

purchase_summary = df["Purchase Amount (USD)"].agg(
    ["count", "mean", "min", "max"]
).round(2)

print(purchase_summary)

count    3900.00
mean       59.76
min        20.00
max       100.00
Name: Purchase Amount (USD), dtype: float64